name: sample_script_2
on:
  workflow_run: 
    workflows: ['sample_script_1', 'Deploy DotNet project to Azure Function App']
    types:
      - completed
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  sample_job_1:
    if: ${{ github.event.workflow_run.sample_script_1.conclusion == 'success' }} && github.event.pull_request.base.ref == 'develop' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: job_1
        run: |
          echo "sample job 212"
      