name: sample_script_2
on:
  workflow_run:
    workflows: ['sample_script_1', 'main_script_1']  # Listen for both workflows
    types:
      - completed
  pull_request:
    types: [closed]
    branches:
      - develop
      - main

jobs:
  sample_job_1:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.workflow == 'sample_script_1' && github.event.pull_request.base.ref == 'develop' }}
    runs-on: ubuntu-latest
    steps:
      - name: job_1
        run: |
          echo "sample job 2 - PR merged into develop"
    
  sample_job_21:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.workflow == 'main_script_1' && github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: job_21
        run: |
          echo "sample job 2 - PR merged into main"
