name: sample_script_2
on:
  workflow_run:
    workflows: ['sample_script_1']
    types:
      - completed
  pull_request:
    types: [closed]
    branches:
      - develop
      - main  # Also add main to listen for PRs merged into main

jobs:
  sample_job_1:
    if: github.event.workflow_run.conclusion == 'success' && github.event.pull_request.base.ref == 'develop' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: job_1
        run: |
          echo "sample job 2 - PR merged into develop"
    
  sample_job_21:
    if: github.event.workflow_run.conclusion == 'success' && github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: job_1
        run: |
          echo "sample job 2 - PR merged into main"
