name: sample_script_2

on:
  workflow_run:
    workflows: 
      - sample_script_1
      - main_script_1
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
 # debug:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Debug GitHub Event
  #      run: |
  #        echo "Event: ${{ toJson(github.event.workflow_run) }}"

  
  sample_job_1:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.name == 'sample_script_1'
    runs-on: ubuntu-latest
    steps:
      - name: Job for Develop Branch
        run: |
          echo "✅ sample job 2 - PR merged into develop"

  sample_job_21:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.name == 'main_script_1'
    runs-on: ubuntu-latest
    steps:
      - name: Job for Main Branch
        run: |
          echo "✅ sample job 2 - PR merged into main"
