name: Deploy DotNet project to Azure Function App
on:
  push:
    branches:
      - develop
 
permissions:
  id-token: write
  contents: read

jobs:
  Dev-Build-Deploy-Function:
    if: github.ref == 'refs/heads/develop'
    environment: Development
    runs-on: windows-latest
    env:
      AZURE_FUNCTIONAPP_NAME: "tf-func-dev-testing-20"
      AZURE_FUNCTIONAPP_PACKAGE_PATH: "BankTransactions"
      DOTNET_VERSION: "6.0.x"
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: "Azure Login"
        run: |
          az login --service-principal --username "${{ secrets.AZURE_CLIENT_ID }}" --password "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANT_ID }}"

      - name: "Setup DotNet ${{ env.DOTNET_VERSION }} Environment"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Resolve Project Dependencies Using Dotnet"
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: "Download Previous Artifact Number"
        uses: actions/download-artifact@v4
        with:
          name: azure-function-app-artifact
          path: artifact_download
        continue-on-error: true

      - name: "Generate Artifact ID"
        run: |
          if (Test-Path "artifact_download/dev_artifact_number.txt") {
            $ARTIFACT_NUMBER = Get-Content "artifact_download/dev_artifact_number.txt"
          } else {
            $ARTIFACT_NUMBER = 0
          }
          
          $NEW_ARTIFACT_NUMBER = $ARTIFACT_NUMBER + 1
          echo "ARTIFACT_NUMBER=$NEW_ARTIFACT_NUMBER" | Out-File -FilePath $Env:GITHUB_ENV -Append

          $DEPLOYED_TIME = (Get-Date).ToString("ddMMyyyy-HHmmss")
          echo "DEPLOYED_TIME=$DEPLOYED_TIME" | Out-File -FilePath $Env:GITHUB_ENV -Append

          $ARTIFACT_ID = "$NEW_ARTIFACT_NUMBER-$DEPLOYED_TIME"
          echo "ARTIFACT_ID=$ARTIFACT_ID" | Out-File -FilePath $Env:GITHUB_ENV -Append

          $ARTIFACT_FILE_NAME = "output-$ARTIFACT_ID.zip"
          echo "ARTIFACT_FILE=$ARTIFACT_FILE_NAME" | Out-File -FilePath $Env:GITHUB_ENV -Append
        shell: pwsh

      - name: "Create ZIP Package"
        run: |
          Compress-Archive -Path "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output/*" -DestinationPath "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/${{ env.ARTIFACT_FILE }}" -Force
        shell: pwsh

      - name: "Fix Permissions (Windows)"
        run: |
          icacls BankTransactions /grant Everyone:F /T /C /Q
        shell: pwsh

      - name: "Upload the artifact file to storage blob container"
        run: |
          if (Test-Path "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/${{ env.ARTIFACT_FILE }}") {
            echo "${{ env.ARTIFACT_FILE }} - ZIP file ready to upload.."
            az storage blob upload --account-name terraform0sa2 --container-name edial-function-app --name dev/${{ env.ARTIFACT_FILE }} --file ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/${{ env.ARTIFACT_FILE }} --overwrite true --auth-mode login
          } else {
            echo "${{ env.ARTIFACT_FILE }} - ZIP file not found."
          }
        shell: pwsh

      - name: "Update the Artifact file number"
        run: |
          $NEW_ARTIFACT_NUMBER = $env:ARTIFACT_NUMBER
          Set-Content -Path "artifact_download/dev_artifact_number.txt" -Value $NEW_ARTIFACT_NUMBER
        shell: pwsh

      - name: "Upload Updated Artifact Number"
        uses: actions/upload-artifact@v4
        with:
          name: azure-function-app-artifact
          path: artifact_download/dev_artifact_number.txt
          retention-days: 365
