name: main_script_1
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sample_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: job_1
        run: |
          echo "main job 1"
      