name: Rollback 2
on: 
  workflow_dispatch:

jobs:
  second_rollback:
    runs-on: windows-latest
    #if: github.event.trigger.base.ref == 'develop' && github.event.pull_request.merged == true
    env:
      AZURE_FUNCTIONAPP_NAME: "tf-func-dev-testing-20"
      AZURE_FUNCTIONAPP_PACKAGE_PATH: "BankTransactions"
      DOTNET_VERSION: "6.0.x"
      STORAGE_ACCOUNT: "terraform0sa1"
      CONTAINER_NAME: "edial-function-app"

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3
      
      # If you want to use Azure RBAC instead of Publish Profile, then uncomment the task below
      - name: "Azure Login"
        run: |
          az login --service-principal --username "d693b53d-6ea8-4242-81eb-deb5d5ce0f64" --password "Xis8Q~iazO69SeWpjFRKAxYhBUMsjkytfMoSCbFk" --tenant "f5f02767-508e-4b78-bc05-2b16c8a081a1"
      
      - name: "Blob Container files List"
        shell: pwsh
        run: |
          $FileList = az storage blob list --account-name "${{ env.STORAGE_ACCOUNT }}" `
                        --container-name "${{ env.CONTAINER_NAME }}" `
                        --query "[].name" --output tsv --auth-mode login

          $SortedFiles = $FileList | Sort-Object {$_ -replace "\D", ""} -Descending

          # Get the second item (n-1), where n = 1-based index
          if ($SortedFiles.Count -ge 2) {
              $NthMinusOneFile = $SortedFiles[1]  # Index 1 gives second item (without "2. " prefix)
          } else {
              Write-Output "Not enough files to get the (n-1)th result."
              exit 1
          }

          Write-Output "Sorted Files:"
          $SortedFiles

          Write-Output "Ready to Download that rollback artifact file: $NthMinusOneFile"

          DOWNLOAD_PATH="${{ github.workspace }}/${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/rollback_zip_files"
          mkdir -p "$DOWNLOAD_PATH"
          mkdir -p "$DOWNLOAD_PATH/rollback_files"

          TARGET_FILE="$DOWNLOAD_PATH/$(basename "$NthMinusOneFile")"

          # Download the file and ensure it exists
          az storage blob download --account-name "${{ env.STORAGE_ACCOUNT }}" `
                    --container-name "${{ env.CONTAINER_NAME }}" `
                    --name "$NthMinusOneFile" --file "$TARGET_FILE" --auth-mode login
      

      - name: "Extract Artifact File"
        uses: hoatruongdev09/extract-zip-github-action@v1.2
        with:
          input-path: $TARGET_FILE
          output-path: $DOWNLOAD_PATH/rollback_files
