name: Rollback 3
on: 
  workflow_dispatch:

jobs:
  second_rollback:
    runs-on: windows-latest
    env:
      AZURE_FUNCTIONAPP_NAME: "tf-func-dev-testing-20"
      AZURE_FUNCTIONAPP_PACKAGE_PATH: "BankTransactions"
      DOTNET_VERSION: "6.0.x"
      STORAGE_ACCOUNT: "terraform0sa1"
      CONTAINER_NAME: "edial-function-app"
      
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: "Azure Login"
        run: |
          az login --service-principal --username "d693b53d-6ea8-4242-81eb-deb5d5ce0f64" --password "Xis8Q~iazO69SeWpjFRKAxYhBUMsjkytfMoSCbFk" --tenant "f5f02767-508e-4b78-bc05-2b16c8a081a1"

      - name: Download & Extract Path creation
        shell: pwsh
        run: |
          Write-Output "${{ github.workspace }}\${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
          $Artifact_DOWNLOAD_PATH="${{ github.workspace }}\${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}\artifact_zip_files"
          $ARTIFACT_EXTRACT_PATH="${{ github.workspace }}\${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}\artifact_files"

          New-Item -ItemType Directory -Force -Path $Artifact_DOWNLOAD_PATH
          New-Item -ItemType Directory -Force -Path $ARTIFACT_EXTRACT_PATH

          if (Test-Path $ARTIFACT_EXTRACT_PATH){
            Write-Output "Artifact Extract Path will created - $ARTIFACT_EXTRACT_PATH"
          } else {
            Write-Output "No Extract path will found."
          }

          if (Test-Path $Artifact_DOWNLOAD_PATH){
            Write-Output "Artifact Download Path will created - $Artifact_DOWNLOAD_PATH"
          } else {
            Write-Output "No Download path is available."
          }

      - name: Find the Rollback artifact file
        shell: pwsh
        run: |
          $FILE_NAME_LIST=az stroage blob list --account-name ${{ env.STORAGE_ACCOUNT }} --container-name ${{ env.CONTAINER_NAME }} --auth-mode login --query "[].name" --output tsv
          Write-Output "$FILE_NAME_LIST"