name: Deploy Mojo API to Func

on:
  push:
    branches:
      - develop
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: ./published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: ""
  CS_PROJ_PATH: OFP_Functions/EDIALIntegration/EDIALIntegration.csproj

  #AZURE_FUNCTIONAPP_NAME_DEV: tf-func-dev-mojo-westus-0001
  #AZURE_FUNCTIONAPP_NAME_TEST: tf-func-test-mojo-westus-0001
  #AZURE_FUNCTIONAPP_NAME_PROD: tf-func-prod-mojo-westus-0001
  STORAGE_ACCOUNT_NAME: "terraform0sa1"
  CONTAINER_NAME: "edial-function-app"
jobs:
  build_develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          creds: '{"clientId":"8987c001-7ceb-4fe5-9b30-a7309cb3b2ab","clientSecret":"l6Z8Q~7BdDLLZIC2IYXb5JlLAx1zy0IERM1~zb2m","subscriptionId":"dbc01991-1c5e-4616-9107-4fe5aae41539","tenantId":"cb7ff8e4-f737-46a0-83c3-2dc17faff09f"}'
      - name: "Azure Login"
        run: |
          az account show
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DOTNET_CORE_VERSION}}
      
      - name: Create the Artifact file name
        run: |
          # Set timezone to PST
          export TZ="America/Los_Angeles"
          
          # Get the current date and time in PST
          DEPLOYED_TIME=$(date +"%Y%m%d%H%M%S")
          
          echo "DEPLOYED_TIME=$DEPLOYED_TIME" >> $GITHUB_ENV

          ARTIFACT_ID="func-api-mojo-dev-$DEPLOYED_TIME"
          echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_ENV

          ARTIFACT_FILE_NAME="$ARTIFACT_ID.zip"
          echo "ARTIFACT_FILE=$ARTIFACT_FILE_NAME" >> $GITHUB_ENV


      - name: Create the Artifact File
        run: |
          zip -r "${{ github.workspace }}/${{ env.ARTIFACT_FILE }}" "${{ github.workspace }}"

      - name: Upload Artifact File
        run: |
          az storage blob upload --account-name ${{ env.STORAGE_ACCOUNT_NAME }} --container-name ${{ env.CONTAINER_NAME }} --name api/dev/${{ env.ARTIFACT_FILE }} --file ${{ github.workspace }}/${{ env.ARTIFACT_FILE }} --overwrite true --auth-mode login
